- pipeline:
    name: check
    post-review: true
    manager: independent
    trigger:
      github:
        - event: pull_request
          action:
            - opened
            - changed
        - event: pull_request
          action:
            - comment
          comment:
            - '^recheck.*$'
    success:
      github:
        comment: true
        status: success
    failure:
      github:
        comment: true
        status: failure
    merge-failure:
      github:
        comment: true
        status: failure
    start:
      github:
        comment: true
        status: pending
    disabled:
      github:
        comment: true


- project:
    name: ashish1211/zuul-test
    check:
      jobs:
        - noop
        - testjob
        - Calculator-master

- job:
    name: base1
    parent: null
    run: base-playbook.yaml

- job:
    name: Calculator-master
    run: Calculator.yaml

- job:
    name: testjob
    run: testjob.yaml
